//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edu.Uninpahu.Arquitectura.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Fijo { get; set; }
        public string Celular { get; set; }
    
        public virtual ICollection<Factura> Factura { get; set; }

        public Cliente(int id, string nombre, string apellido, string fijo, String celular)
        {
            this.Id = id;
            this.Nombre = nombre;
            this.Apellido = apellido;
            this.Fijo = fijo;
            this.Celular = celular;
    
        }
        public Cliente()
        {
            this.Factura = new HashSet<Factura>();
        }



    }
}
