//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edu.Uninpahu.Arquitectura.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Factura
    {
        public int Id { get; set; }
        public int IdFactura { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorIva { get; set; }
        public decimal Subtotal { get; set; }
        public int IdProducto { get; set; }

        public D_Factura( int idFactura, int cantidad, decimal valorIva, decimal subtotal, int idProducto)
        {
            IdFactura = idFactura;
            Cantidad = cantidad;
            ValorIva = valorIva;
            Subtotal = subtotal;
            IdProducto = idProducto;          
        }

        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
