//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edu.Uninpahu.Arquitectura.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public string Cargo { get; set; }
        public string Fijo { get; set; }
        public string Celular { get; set; }

        public Empleado(int id, string nombre, string apellido, string direccion, string cargo, string fijo, string celular)// ICollection<Factura> factura)
        {
            Id = id;
            Nombre = nombre;
            Apellido = apellido;
            Direccion = direccion;
            Cargo = cargo;
            Fijo = fijo;
            Celular = celular;
            //Factura = factura;
        }

        public virtual ICollection<Factura> Factura { get; set; }
    }
}
