//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edu.Uninpahu.Arquitectura.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.D_Factura = new HashSet<D_Factura>();
        }    

        public int Id { get; set; }
        public int IdCliente { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<D_Factura> D_Factura { get; set; }
        public virtual Empleado Empleado { get; set; }

        public Factura(int idCliente, int idEmpleado, DateTime fecha)
        {
            IdCliente = idCliente;
            IdEmpleado = idEmpleado;
            Fecha = fecha;
        }
    }
}
