//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edu.Uninpahu.Arquitectura.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
       
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorUnitario { get; set; }
        public int PorcetajeIva { get; set; }

        public Producto(int codigo, string nombre, int cantidad, decimal valorUnitario, int porcetajeIva)//, ICollection<D_Factura> d_Factura)
        {
            Codigo = codigo;
            Nombre = nombre;
            Cantidad = cantidad;
            ValorUnitario = valorUnitario;
            PorcetajeIva = porcetajeIva;
           // D_Factura = d_Factura;
        }

        public Producto()
        {
            this.D_Factura = new HashSet<D_Factura>();
        }
        public virtual ICollection<D_Factura> D_Factura { get; set; }
    }
}
