//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edu.Uninpahu.Arquitectura.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    using Edu.Uninpahu.Arquitectura.Dominio;
    
    public partial class FACTURAEntities : DbContext
    {
        public FACTURAEntities()
            : base("name=FACTURAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> CLIENTE { get; set; }
        public DbSet<D_Factura> D_FACTURA { get; set; }
        public DbSet<Empleado> EMPLEADO { get; set; }
        public DbSet<Factura> FACTURA { get; set; }
        public DbSet<Producto> PRODUCTO { get; set; }
    }
}
