CREATE TABLE [dbo].[CLIENTE]
(
	[ID_CLIENTE] INT NOT NULL PRIMARY KEY, 
    [NOMBRE] VARCHAR(50) NOT NULL, 
    [APELLIDO] VARCHAR(50) NOT NULL, 
    [FIJO] CHAR(10) NOT NULL, 
    [CELULAR] CHAR(10) NOT NULL
)
