CREATE TABLE [dbo].[D_FACTURA]
(
	[ID_D_FACTURA] INT NOT NULL IDENTITY, 
    [ID_FACTURA_FK] INT NOT NULL, 
    [CANTIDAD] INT NOT NULL, 
    [VALOR_IVA] DECIMAL NOT NULL, 
    [SUBTOTAL] DECIMAL NOT NULL, 
    [ID_PRODUCTO_FK] INT NOT NULL, 
    CONSTRAINT [PK_D_FACTURA] PRIMARY KEY ([ID_D_FACTURA]), 
    CONSTRAINT [FK_D_FACTURA_ToFACTURA] FOREIGN KEY ([ID_FACTURA_FK]) REFERENCES [FACTURA]([ID_FACTURA]), 
    CONSTRAINT [FK_D_FACTURA_ToPRODUCTO] FOREIGN KEY ([ID_PRODUCTO_FK]) REFERENCES [PRODUCTO]([CODIGO])
)
