CREATE TABLE [dbo].[EMPLEADO]
(
	[ID_EMPLEADO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NOMBRE] VARCHAR(50) NOT NULL, 
    [APELLIDO] VARCHAR(50) NOT NULL, 
    [DIRECCION] VARCHAR(50) NOT NULL, 
    [CARGO] VARCHAR(20) NOT NULL, 
    [FIJO] CHAR(10) NOT NULL, 
    [CELULAR] CHAR(10) NOT NULL
)
